# All answer words are exactly 5 letters. Verified.

easy_words = [
    "APPLE", "TRAIN", "HOUSE", "MOUSE", "WATER",
    "PLANT", "SMILE", "BREAD", "GRASS", "RIVER",
    "CHAIR", "TABLE", "LIGHT", "HEART", "MUSIC",
    "NIGHT", "DREAM", "WORLD", "PEACE", "TRUTH",
    "STONE", "CLOUD", "FLAME", "STORM", "BEACH",
    "CLOCK", "FLOOD", "FROST", "GIANT", "GRAPE",
    "HONEY", "LEMON", "MAPLE", "OCEAN", "PIANO",
    "QUEEN", "RANCH", "SUGAR", "TIGER", "VOICE",
]

medium_words = [
    "YACHT", "ZEBRA", "VAGUE", "QUICK", "JUMBO",
    "KNACK", "FLOCK", "GLOVE", "THICK", "SPARK",
    "BLINK", "CLERK", "DRAFT", "GHOST", "KNIFE",
    "MAGIC", "ONION", "PIZZA", "QUOTE", "ROBOT",
    "BLUFF", "CHUNK", "DWARF", "ENVOY", "FJORD",
    "GRUMP", "HANDY", "ITCHY", "JAZZY", "KINKY",
    "LLAMA", "MURKY", "NUTTY", "OXIDE", "PERKY",
    "QUIRK", "ROCKY", "SCAMP", "TROVE", "UNZIP",
]

hard_words = [
    # Palindromes and tricky patterns
    "KAYAK", "CIVIC", "RADAR", "LEVEL", "ROTOR",
    "MADAM", "REFER", "STATS", "TENET", "WOWED",
    # Double letters
    "FLUFF", "MUMMY", "PUPPY", "QUEUE", "PIZZA",
    # Consonant-heavy / rare combos
    "CRYPT", "GLYPH", "NYMPH", "TRYST", "WALTZ",
    "ZILCH", "EXPEL", "SQUAB", "VOUCH", "WHIFF",
    "BOXER", "CYCLE", "GAWKY", "JAZZY", "KNEEL",
    "LYMPH", "MYRRH", "OXIDE", "PROXY", "QUERY",
]

WORD_LISTS = {
    "easy":      easy_words,
    "moderate":  medium_words,
    "difficult": hard_words,
    "prodigy":   hard_words,
}

# ── Valid guesses (superset of answers) ───────────────────────────────────────
# Any 5-letter word the player may submit as a guess.
_EXTRA_VALID = {
    "ABOUT", "ABOVE", "ABUSE", "ACHES", "ACORN", "ACRES", "ACTED", "ACUTE",
    "ADAGE", "ADAPT", "ADDED", "ADEPT", "ADMIT", "ADOBE", "ADOPT", "ADORE",
    "ADULT", "AFTER", "AGAIN", "AGATE", "AGAVE", "AGENT", "AGILE", "AGING",
    "AGONY", "AGREE", "AHEAD", "AIDED", "AIMED", "AIRED", "AISLE", "ALARM",
    "ALBUM", "ALERT", "ALGAE", "ALIGN", "ALIKE", "ALIVE", "ALLAY", "ALLEY",
    "ALLOW", "ALLOY", "ALONE", "ALONG", "ALOOF", "ALOUD", "ALTER", "AMAZE",
    "AMEND", "ANGEL", "ANGER", "ANGLE", "ANGRY", "ANIME", "ANKLE", "ANNOY",
    "ANTIC", "ANVIL", "APART", "APTLY", "ARENA", "ARGUE", "AROMA", "ARRAY",
    "ARROW", "ASIDE", "ASKED", "ATTIC", "AUDIO", "AUDIT", "AVERT", "AVOID",
    "AWARD", "AWARE", "AWFUL", "AXIAL", "AZURE", "BADGE", "BADLY", "BAGEL",
    "BAKED", "BAKER", "BASIC", "BASIS", "BATCH", "BATHE", "BEGAN", "BEGIN",
    "BELLE", "BELOW", "BENCH", "BIOME", "BIRCH", "BISON", "BLAND", "BLAST",
    "BLAZE", "BLEAK", "BLEND", "BLESS", "BLIND", "BLISS", "BLOWN", "BLUNT",
    "BOARD", "BOGUS", "BONUS", "BOOST", "BOOZE", "BORED", "BOUND", "BRACE",
    "BRAND", "BRAVE", "BRAVO", "BRAWN", "BRAZE", "BREAK", "BREAM", "BREED",
    "BRINE", "BRISK", "BROKE", "BROOK", "BROOM", "BROWN", "BRUSH", "BRUTE",
    "BULGE", "BUGLE", "BUILD", "BUILT", "BULKY", "BUNCH", "BURNS", "BURST",
    "BUYER", "CABIN", "CAMEL", "CANDY", "CARGO", "CARRY", "CARVE", "CAUSE",
    "CEDAR", "CHAMP", "CHAOS", "CHARM", "CHASM", "CHEAP", "CHEAT", "CHECK",
    "CHEEK", "CHEER", "CHESS", "CHEST", "CHILI", "CHILL", "CHIMP", "CHINA",
    "CHIPS", "CHORE", "CIVIC", "CLAIM", "CLAMP", "CLASH", "CLASS", "CLEAN",
    "CLEAR", "CLEFT", "CLIMB", "CLING", "CLOSE", "CLOTH", "COAST", "COMET",
    "COMIC", "COMMA", "CORAL", "COUCH", "COULD", "COUNT", "COURT", "COVER",
    "COVET", "CRAFT", "CRANE", "CRASH", "CRAZY", "CREAM", "CRISP", "CRONE",
    "CROSS", "CROWD", "CROWN", "CRUEL", "CRUMB", "CRUSH", "CRUST", "CUBIC",
    "CURRY", "CURVE", "DANDY", "DAUNT", "DECAY", "DECOY", "DEFER", "DEITY",
    "DELAY", "DELTA", "DENSE", "DEPOT", "DEPTH", "DERBY", "DETOX", "DEVIL",
    "DIGIT", "DINER", "DINGO", "DISCO", "DITTY", "DIVER", "DIZZY", "DODGE",
    "DOGMA", "DONOR", "DOUBT", "DOUGH", "DOWRY", "DRAIN", "DRAPE", "DRAWL",
    "DRAWN", "DREAD", "DRINK", "DROOP", "DROVE", "DROWN", "DRUID", "DRUNK",
    "DUNCE", "DUNES", "EARLY", "EARTH", "EASEL", "EJECT", "ELBOW", "ELDER",
    "ELITE", "EMAIL", "EMBER", "EMPTY", "ENACT", "ENEMY", "ENJOY", "EPOCH",
    "EQUIP", "ERUPTION", "ESSAY", "ETHER", "EVADE", "EVENT", "EVERY", "EXACT",
    "EXALT", "EXERT", "EXILE", "EXIST", "EXTRA", "FABLE", "FACET", "FAITH",
    "FANCY", "FARCE", "FATAL", "FEAST", "FEIGN", "FERAL", "FERRY", "FETCH",
    "FEVER", "FIBER", "FIELD", "FIEND", "FIFTH", "FIFTY", "FIGHT", "FINAL",
    "FIRST", "FIXED", "FIZZY", "FLANK", "FLASH", "FLASK", "FLEET", "FLESH",
    "FLINT", "FLOAT", "FLOOR", "FLOUR", "FLOWN", "FLUID", "FLUKE", "FLUTE",
    "FOAMY", "FOCUS", "FORGE", "FORGO", "FORTE", "FORUM", "FOUND", "FRAME",
    "FRANK", "FRAUD", "FREAK", "FRESH", "FRILL", "FRISK", "FRONT", "FROTH",
    "FROZE", "FRUIT", "FUNGI", "FUNKY", "FUNNY", "FURRY", "FUSSY", "FUZZY",
    "GAUDY", "GAUZE", "GAVEL", "GEEKY", "GENRE", "GIDDY", "GIRLISH", "GIVEN",
    "GIZMO", "GLAND", "GLARE", "GLASS", "GLEAN", "GLEAM", "GLIDE", "GLINT",
    "GLOAT", "GLOBE", "GLOOMY", "GLOSS", "GLUED", "GNOME", "GOING", "GRACE",
    "GRADE", "GRAIN", "GRAND", "GRANT", "GRASP", "GRAZE", "GREAT", "GREED",
    "GREET", "GRIEF", "GRILL", "GRIPE", "GRIMY", "GROAN", "GROIN", "GROPE",
    "GROUT", "GROVE", "GROWL", "GRUEL", "GRUFF", "GRUNGE", "GUARD", "GUAVA",
    "GUILE", "GUISE", "GULCH", "GUSTO", "GUSTY", "GYPSY", "HABIT", "HANKY",
    "HAPPY", "HARSH", "HASTE", "HAUNT", "HAVEN", "HAVOC", "HAZE", "HEAVY",
    "HEDGE", "HEIST", "HENCE", "HERBS", "HERON", "HINTS", "HIPPO", "HITCH",
    "HOLLY", "HONOR", "HOUND", "HUMAN", "HUMID", "HURRY", "HYPER", "IDEAL",
    "IDIOM", "IDIOT", "IGLOO", "IMAGE", "IMPLY", "INDEX", "INDIE", "INFER",
    "INFIX", "INNER", "INPUT", "INTER", "INTRO", "IONIC", "IRATE", "IRONY",
    "ISSUE", "IVORY", "JAUNT", "JEWEL", "JIFFY", "JOINT", "JOKER", "JOLLY",
    "JOUST", "JUDGE", "JUICE", "JUICY", "KARMA", "KAYAK", "KIOSK", "KITTY",
    "KNELT", "KNOWN", "KOALA", "LABEL", "LADEN", "LADLE", "LANCE", "LAPSE",
    "LARGE", "LARVA", "LASER", "LATCH", "LATER", "LEAFY", "LEAKY", "LEARN",
    "LEAST", "LEAVE", "LEDGE", "LEGAL", "LEMON", "LIEGE", "LINER", "LINGO",
    "LIVER", "LLAMA", "LOBBY", "LODGE", "LOGIC", "LOOSE", "LORRY", "LOSER",
    "LOUSY", "LOVER", "LOWER", "LUCKY", "LURID", "LUSTY", "LYRIC", "MANOR",
    "MAPLE", "MARCH", "MARRY", "MARSH", "MATCH", "MATTE", "MAXIM", "MAYBE",
    "MEDIA", "MERCY", "MERGE", "MERIT", "METAL", "MIGHT", "MIMIC", "MINCE",
    "MINOR", "MINUS", "MIRTH", "MOCHA", "MODEL", "MOIST", "MONEY", "MONTH",
    "MORAL", "MORON", "MOSSY", "MOTIF", "MOTOR", "MOTTO", "MOUND", "MOURN",
    "MOUTH", "MUDDY", "MULCH", "MURKY", "NANNY", "NASAL", "NASTY", "NAVAL",
    "NIFTY", "NOBLE", "NOISE", "NORTH", "NOVEL", "NUDGE", "NURSE", "NYMPH",
    "OCCUR", "ODDLY", "OFFER", "OMEGA", "ONSET", "OPTIC", "ORBIT", "ORCHID",
    "ORDER", "ORGAN", "OTHER", "OUGHT", "OUTER", "OVERT", "OWNER", "OXIDE",
    "OZONE", "PADDY", "PANIC", "PAPAL", "PASTE", "PATCH", "PATIO", "PATSY",
    "PAUSE", "PEACH", "PEARL", "PETAL", "PETTY", "PHASE", "PHONE", "PHOTO",
    "PIGMY", "PILOT", "PINCH", "PITCH", "PIXEL", "PIXEL", "PLACE", "PLAID",
    "PLAIN", "PLANE", "PLANK", "PLATE", "PLAZA", "PLEAD", "PLUCK", "PLUMB",
    "PLUME", "PLUNK", "PLUSH", "POACH", "PODGY", "POINT", "POISE", "POKER",
    "POLAR", "POPPY", "PORCH", "POSED", "POUCH", "POWER", "PRANK", "PRESS",
    "PRICE", "PRICK", "PRIDE", "PRIME", "PRISM", "PRIVY", "PROBE", "PRONE",
    "PROOF", "PROSE", "PROUD", "PRUDE", "PRUNE", "PSALM", "PULPY", "PULSE",
    "PUNCH", "PUNY",  "PURGE", "PUSHY", "QUALM", "QUARRY", "QUEST", "QUILL",
    "QUIRK", "QUOTA", "RACER", "RADAR", "RADIX", "RAINY", "RALLY", "RANGE",
    "RAPID", "RASPY", "RATIO", "RAVEN", "REACH", "REACT", "READY", "REALM",
    "RECAP", "REIGN", "RELAX", "REPAY", "REPEL", "RESET", "RESIN", "RETCH",
    "RETRY", "REVUE", "RISKY", "RITZY", "RIVAL", "ROGUE", "ROMAN", "ROUGE",
    "ROUGH", "ROUND", "ROUTE", "ROWDY", "RUGBY", "RULER", "RUMOR", "RUSTY",
    "SADLY", "SAINT", "SALAD", "SAUCE", "SAVOR", "SAVVY", "SCALD", "SCALE",
    "SCALP", "SCANT", "SCARE", "SCARF", "SCENE", "SCOOP", "SCOPE", "SCORE",
    "SCORN", "SCOUT", "SCOWL", "SCRUB", "SEIZE", "SENSE", "SERUM", "SERVE",
    "SETUP", "SEVEN", "SHAFT", "SHAKE", "SHAME", "SHAPE", "SHARE", "SHARK",
    "SHARP", "SHAWL", "SHEAR", "SHEEN", "SHEEP", "SHELF", "SHELL", "SHIFT",
    "SHINE", "SHIRE", "SHIRT", "SHOAL", "SHOCK", "SHORE", "SHOUT", "SHOVE",
    "SHRED", "SHREW", "SHRUB", "SHRUG", "SHUCK", "SIGHT", "SINCE", "SIXTH",
    "SIXTY", "SIZED", "SKILL", "SKULL", "SKUNK", "SLANT", "SLASH", "SLATE",
    "SLAVE", "SLEEK", "SLEEP", "SLEET", "SLEPT", "SLIDE", "SLIME", "SLING",
    "SLINK", "SLOPE", "SLOTH", "SLUMP", "SMART", "SMASH", "SMELL", "SNAIL",
    "SNARE", "SNARL", "SNEAK", "SNEER", "SNIFF", "SNORE", "SNORT", "SNOUT",
    "SOGGY", "SOLAR", "SOLID", "SOLVE", "SONIC", "SORRY", "SOUTH", "SPACE",
    "SPARE", "SPEAK", "SPEAR", "SPECK", "SPEED", "SPELL", "SPEND", "SPICE",
    "SPINE", "SPITE", "SPORE", "SPORT", "SPRAY", "SQUAD", "SQUAT", "SQUID",
    "STACK", "STAFF", "STAIN", "STALE", "STALL", "STAMP", "STAND", "STANK",
    "STARK", "START", "STASH", "STEAK", "STEAM", "STEEL", "STEEP", "STEER",
    "STERN", "STIFF", "STILL", "STING", "STINK", "STOCK", "STOMP", "STOOD",
    "STOOP", "STORE", "STOVE", "STRAP", "STRAW", "STRAY", "STRIP", "STRUT",
    "STUCK", "STUDY", "STUFF", "STUMP", "STUNG", "STUNK", "STUNT", "STYLE",
    "SUAVE", "SULKY", "SUNNY", "SUPER", "SWAMP", "SWEAR", "SWEAT", "SWEEP",
    "SWEET", "SWEPT", "SWIFT", "SWILL", "SWIPE", "SWIRL", "SWOOP", "TABOO",
    "TALON", "TANGO", "TAPIR", "TAUNT", "TEETH", "TEMPO", "TENSE", "THANK",
    "THEIR", "THERE", "THESE", "THINK", "THIRD", "THREE", "THREW", "THROW",
    "THUMB", "THUMP", "TIARA", "TIDAL", "TIMID", "TOADIE", "TODAY", "TOKEN",
    "TONIC", "TOPAZ", "TORSO", "TOTAL", "TOUCH", "TOUGH", "TOWEL", "TOXIC",
    "TRACE", "TRADE", "TRAIL", "TRAMP", "TRASH", "TRIAL", "TRIBE", "TRICK",
    "TRIED", "TROLL", "TROOP", "TROUT", "TRUCE", "TRULY", "TRUMP", "TRUNK",
    "TUNED", "TUNIC", "TURBO", "TUTOR", "TWEAK", "TWEED", "TWIRL", "ULTRA",
    "UNCLE", "UNDER", "UNDUE", "UNION", "UNITY", "UNTIL", "UPPER", "UPSET",
    "URBAN", "USAGE", "USHER", "USUAL", "UTTER", "VALID", "VALOR", "VALUE",
    "VALVE", "VAULT", "VENOM", "VERSE", "VIDEO", "VIGOR", "VILLA", "VIOLA",
    "VIRAL", "VISOR", "VISTA", "VOMIT", "VOTER", "VOUCH", "VOWEL", "WAGER",
    "WAKEN", "WATCH", "WATER", "WEARY", "WEAVE", "WEDGE", "WEEDY", "WEIRD",
    "WHALE", "WHACK", "WHEAT", "WHIRL", "WHOLE", "WHOSE", "WIDER", "WINDY",
    "WITCH", "WITTY", "WOMAN", "WOODS", "WORDY", "WORSE", "WORST", "WORTH",
    "WOULD", "WRACK", "WRATH", "WREAK", "WRECK", "WRIST", "WROTE", "YACHT",
    "YEARN", "YEAST", "YIELD", "YOUNG", "YOUTH", "ZESTY", "ZONAL",
}

# Combine all answer words + extra valid guesses into one lookup set
_ALL_ANSWERS = set(easy_words + medium_words + hard_words)
VALID_GUESSES: set = _ALL_ANSWERS | _EXTRA_VALID


def get_word(difficulty: str) -> str:
    import random
    words = WORD_LISTS.get(difficulty.lower(), easy_words)
    return random.choice(words).upper()
